### ISSUE TITLE
fail to run fastsolver.m example

### ISSUE THREAD

**Issue by nate271** [victorlei/smop#116]
I've cloned the project, installed a fresh python 2.7, added it to the path (win10), went to the smop folder and when trying
`python main.py fastsolver.m -o fastsolver.py`  I got 

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import lexer
  File "C:\Users\NatanPULSE\Documents\GitHub\smop\smop\lexer.py", line 8, in <module>
    import options
  File "C:\Users\NatanPULSE\Documents\GitHub\smop\smop\options.py", line 4, in <module>
    from version import __version__
ImportError: No module named version

**Comment by victorlei** [comment]
Fixed in 0.40
