### ISSUE TITLE
PyCompileError: Sorry: IndentationError: unexpected indent (m.py, line 6)

### ISSUE THREAD

**Issue by l333wang** [victorlei/smop#118]
[root@localhost smop]# python main.py m.m
Traceback (most recent call last):
  File "main.py", line 98, in main
    py_compile.compile(f,doraise=True)
  File "/usr/lib64/python2.7/py_compile.py", line 117, in compile
    raise py_exc
PyCompileError: Sorry: IndentationError: unexpected indent (m.py, line 6)
Errors: 1

**Comment by victorlei** [comment]
Please submit m.m file
