### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by KamiDuck** [victorlei/smop#184]
While trying to convert several matlab files to python I got the following error. I cannot for the life of me figure out where it is going wrong.

c:\users\balun\anaconda3\lib\site-packages\ply\lex.py:760: FutureWarning: Possible nested set at position 65
  c = re.compile('(?P<%s>%s)' % (fname, _get_regex(f)), self.reflags)
c:\users\balun\anaconda3\lib\site-packages\ply\lex.py:498: FutureWarning: Possible nested set at position 118
  lexre = re.compile(regex, reflags)
Traceback (most recent call last):
  File "c:\users\balun\anaconda3\lib\site-packages\smop\main.py", line 66, in main
    G = resolve.resolve(stmt_list)
  File "c:\users\balun\anaconda3\lib\site-packages\smop\resolve.py", line 51, in resolve
    G = as_networkx(t)
  File "c:\users\balun\anaconda3\lib\site-packages\smop\resolve.py", line 39, in as_networkx
    if u.lexpos < v.lexpos:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
Errors: 1

**Comment by Rohanjos97** [comment]
I'm also facing the same issue. @KamiDuck, did you find any workaround for this?
