### ISSUE TITLE
smop command not found even after installation

### ISSUE THREAD

**Issue by TomaOC** [victorlei/smop#186]
Hi victorlei,

I successfully downloaded and installed (or so I thought) smop, but I am encountering the following issues whenever I try to use it:
Any `smop` etc. command yields
`-bash: smop: command not found`
while attempting
`python main.py file.m`
from within smop/smop/ yields
`Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from . import options
ValueError: Attempted relative import in non-package`
Trying
`python3 main.py file.m`
gives
`Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from . import options
ImportError: cannot import name 'options' from '__main__' (main.py)`

Any ideas?

Thanks in advance!

**Comment by adienxy** [comment]
SAME Q
