### ISSUE TITLE
No module named 'version'

### ISSUE THREAD

**Issue by josephcslater** [victorlei/smop#76]
Using pip, or downloading the current  state and using `python setup.py install --user` both end up failing when trying to call it from the command line. 

I'm not sure how to go about fixing this. 

MacOS X 10.11

log
------
    [jslater@norma ~]$ smop -V
    Traceback (most recent call last):
      File "/Users/jslater/Library/Python/3.4/bin/smop", line 9, in <module>
        load_entry_point('smop==0.0.0', 'console_scripts', 'smop')()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
        return ep.load()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
        return self.resolve()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/Users/jslater/Library/Python/3.4/lib/python/site-packages/smop-0.0.0-py3.4.egg/smop/__init__.py", line 4, in <module>
    ImportError: No module named 'version'

**Comment by josephcslater** [comment]
Apparently this is an issue with Python 3 (I'm using 3.4), but not with 2.7.

**Comment by victorlei** [comment]
Fixed in 0.28
