### ISSUE TITLE
simple scheduling algorithm - problem to install (easy_install or pip)

### ISSUE THREAD

**Issue by andrejunges** [victorlei/smop#91]
Hey, Im trying to use this compiler but Im getting errors to install. I've already tried a bunch of things but still getting errors with `pip` or `easy_install`.

**easy_install**

```
smop: error: unrecognized arguments: -q --dist-dir /var/folders/s7/mdq9w9q150q_4g5mwt5g949c0000gn/T/easy_install-4Vcqub/smop-0.29/egg-dist-tmp-QoDaT1
error: Setup script exited with 2
```

**pip**

```
   smop: error: unrecognized arguments: --egg-base pip-egg-info
Cleaning up...
Command "python setup.py egg_info" failed with error code 2 in /private/var/folders/s7/mdq9w9q150q_4g5mwt5g949c0000gn/T/pip-build-jhT4tW/smop/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 601, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 425, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 2 in /private/var/folders/s7/mdq9w9q150q_4g5mwt5g949c0000gn/T/pip-build-jhT4tW/smop/
```

ps: I've already installed its dependencies, but it made no difference

any help would be really appreciated

**Comment by RobBW** [comment]
Try the advice here:  http://stackoverflow.com/questions/31719816/pip-fails-to-install-anything-error-invalid-command-egg-info
I had the same error with smop install and found this info. I'm away from home now for a month and can't work on it.

Regards
Rob Wilkinson

**Comment by andrejunges** [comment]
Unfortunately neither the solutions worked for me 😢 

Its worth to mention Im using a mac
OS: macOS Sierra
version: 10.12

**Comment by RobBW** [comment]
I am on El Capitan. I assume you know that Apple has blocked access to usr/local in the recent releases of OsX. It may have toughened things more with Sierra. I Know that this messes up some standard UNIX based installers. Hope this helps.

Regards
Rob Wilkinson

**Comment by andrejunges** [comment]
Hmm, I've just set up an VM with Ubuntu 16.04.1.
And even in this 100% clean environment I'm getting the same error. (for both pip and easy_install)

I tried to update `pip` and `setuo-tools`.. tried to install `ez_setup.py` and `ply`.
Unfortunately still cant get it working.

Thanks

**Comment by iglesias** [comment]
I am facing the same error in native Ubuntu 16.04.

```
$ sudo easy_install smop --user
Searching for smop
Reading https://pypi.python.org/simple/smop/
Downloading https://pypi.python.org/packages/52/f3/ec2f6ab31717bbf9e38040f9937febc2be43d6aac2be782250b617d287c2/smop-0.29.tar.gz#md5=732047fbcfe788a09fbc7f780ac28c1a
Best match: smop 0.29
Processing smop-0.29.tar.gz
Writing /tmp/easy_install-MCQ62N/smop-0.29/setup.cfg
Running smop-0.29/setup.py -q bdist_egg --dist-dir /tmp/easy_install-MCQ62N/smop-0.29/egg-dist-tmp-Yf8HCh
usage: 

    smop [options][file.m ...file.m][-l file.py...]
             or
    smop [options] library.tar [-l file.py...]
smop: error: unrecognized arguments: -q --dist-dir /tmp/easy_install-MCQ62N/smop-0.29/egg-dist-tmp-Yf8HCh
error: Setup script exited with 2
```

**Comment by victorlei** [comment]
i fixed a bunch of installation problems. please reopen if still broken
